In [3]:
import numpy as np

In [36]:
cartasCulpable=['Mora','Blanco','Amapola','Prado','Rubio','Celeste']
cartasLugar=['Patio','Estudio','Comedor','Garaje','Salon','Dormitorio']
cartasMotivo=['Racismo','Homofobia','Transfobia','Xenofobia','Sexismo','Discriminacion por discapacidad']

#print(cartasCulpable)
#print(cartasLugar)
#print(cartasMotivo)
cards = [cartasCulpable,cartasLugar,cartasMotivo]
for elem in cards:
    print(elem)

['Mora', 'Blanco', 'Amapola', 'Prado', 'Rubio', 'Celeste']
['Patio', 'Estudio', 'Comedor', 'Garaje', 'Salon', 'Dormitorio']
['Racismo', 'Homofobia', 'Transfobia', 'Xenofobia', 'Sexismo', 'Discriminacion por discapacidad']


In [17]:
def createKb():
    kb = np.zeros((3,6))
    for i in range(18):
        kb.itemset(i,-1)
    #print(kb)
    return kb
Example = createKb()
#print(type(Example))

In [18]:
def changeValue(kb,cardType,card,info):
    if info:
        kb.itemset((cardType,card),1)
    else:
        kb.itemset((cardType,card),0)

changeValue(Example,0,1,True)
changeValue(Example,0,2,True)
print(Example)


[[-1.  1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]]


In [22]:
def seeSecurity(kb,cardType):
    count0 = 0
    for i in range(6):
        if kb[cardType,i] == 0:
            count0 +=1
        if kb[cardType,i] == 1:
            print("Card {0} is part of the answer".format(kb[cardType,i]))
            return
    if count0 == 5:
        for i in range(6):
            if kb[cardType,i] == -1:
                print("Card {0} is part of the answer".format(kb[cardType,i]))

seeSecurity(Example,0)

Example2 = createKb()
for i in range(5):
    changeValue(Example2,0,i,False)
seeSecurity(Example2,0)
print(Example2)

Card 1.0 is part of the answer
Card -1.0 is part of the answer
a
[[ 0.  0.  0.  0.  0. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]]
