## Aviso

Mirar el archivo utils.py para informacion mas detallada de las funciones y para ver funciones que son necesarias para el funcionamiento del juego

# Imports

In [1]:
import numpy as np

# Funciones

## Crear lista de cartas
Se crea una lista de cartas, para este ejemplo no es muy util pero es necesario para el juego

In [12]:
def cartas():
    cartasCulpable=['Mora','Blanco','Amapola','Prado','Rubio','Celeste']
    cartasLugar=['Patio','Estudio','Comedor','Garaje','Salon','Dormitorio']
    cartasMotivo=['Racismo','Homofobia','Transfobia','Xenofobia','Sexismo','Discriminacion por discapacidad']

    cartas = [cartasCulpable,cartasLugar,cartasMotivo]
    return cartas
lcartas = cartas()
for i in range(3):
    print(lcartas[i])


['Mora', 'Blanco', 'Amapola', 'Prado', 'Rubio', 'Celeste']
['Patio', 'Estudio', 'Comedor', 'Garaje', 'Salon', 'Dormitorio']
['Racismo', 'Homofobia', 'Transfobia', 'Xenofobia', 'Sexismo', 'Discriminacion por discapacidad']


## Crear base de conocimiento
Se crea una base de conocimiento, esta tiene forma de una matriz de 3x6, ya que esa son la cantidad de cartas en el juego.
La base de conocimiento tiene datos iniciales en -1, ya que este representa falta de informacion

In [13]:
def createKb():
    kb = np.zeros((3,6))
    for i in range(18):
        kb.itemset(i,-1)
    #print(kb)
    return kb
Example = createKb()
#print(type(Example))

## Cambiar valores
Cambia los valores a la base de conocimiento.
0 representa que esa carta no es la respuesta
1 representa que esa carta es parte de la respuesta

In [9]:
def changeValue(kb, card, info):
    if info:
        kb.itemset(card, 1)
    else:
        kb.itemset(card, 0)
    return kb

Example = changeValue(Example,(0,1),True)
Example = changeValue(Example,(0,2),False)
Example = changeValue(Example,(1,2),True)
print(Example)


[[-1.  1.  0. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]]


## Seguridad
Esta funcion muestra si nuestra base de conocimiento tiene certeza sobre algun tipo de cartas
Se basa en la regla solo una carta de cada tipo es la respuesta correcta, esto se puede entender como:

-Solo existe una carta de culpables que es el culpable:  ∃x. (CartaCulpable(x) ∧ Culpable(x))

-Solo existe una carta de lugares que es el lugar:  ∃x. (CartaLugar(x) ∧ Lugar(x))

-Solo existe una carta de motivos que es el motivo:  ∃x. (CartaMotivo(x) ∧ Motivo(x))

In [16]:
def seeSecurity(kb,cardType,cartas):
    count0 = 0
    for i in range(6):
        if kb[cardType,i] == 0:
            count0 +=1
        if kb[cardType,i] == 1:
            mensaje="Carta {0} es parte de la respuesta".format(cartas[cardType][i])
            return kb,mensaje
    if count0 == 5:
        for i in range(6):
            if kb[cardType,i] == -1:
                kb = changeValue(kb,(cardType,i),True)
                mensaje="Carta {0} es parte de la respuesta".format(cartas[cardType][i])
                return kb,mensaje
    mensaje="La base de conocimiento no tiene informacion suficiente sobre "
    if cardType==0:
        mensaje+="Los culpables"
    elif cardType==1:
        mensaje+="El lugar"
    else:
        mensaje+="El motivo" 
    return kb,mensaje

seeSecurity(Example,0,lcartas)

Example2 = createKb()
for i in range(5):
    Example2 = changeValue(Example2,(0,i),False)
Example2,m=seeSecurity(Example2,0,lcartas)
print(m)
#print(Example2)
Example2,m=seeSecurity(Example2,1,lcartas)
print(m)

Carta Celeste es parte de la respuesta
La base de conocimiento no tiene informacion suficiente sobre El lugar


## Verificación

Revisa si la acusacion de un jugador es correcta.

Esta solo es correcta si el jugador acierta el culpable, el motivo y el lugar.

∀x. (Culpable(x) ∧ Lugar(y) ∧ Motivo (z) →RespuestaCorrecta(x,y,z))


In [ ]:
def verification(numeroPersona,numeroMotivo,numeroLugar,cartasganadoras):

    if numeroPersona not in cartasganadoras:
        mensaje="Perdiste"
        return mensaje
    if numeroMotivo not in cartasganadoras:
        mensaje="Perdiste"
        return mensaje
    if numeroLugar not in cartasganadoras:
        mensaje="Perdiste"
        return mensaje
    mensaje="Ganaste"
    return mensaje
    